# Generated by Django 5.2.1 on 2025-05-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mediafile',
            name='categories',
            field=models.ManyToManyField(to='pages.category'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='tags',
            field=models.ManyToManyField(to='pages.tag'),
        ),
    ]
