# Generated by Django 5.2.1 on 2025-05-20 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_category_tag_mediafile_categories_mediafile_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
